COEFF_ASSISTED = 0.5
COEFF_PARTIAL = 0.33

MUSCLES = {
    "Clavicular Head": "Chest",
    "Sternal Head": "Chest",
    "Latissimus Dorsi": "Back",
    "Upper and Mid Trapezius": "Back",
    "Lower Trapezius and Rhomboids": "Back",
    "Erectors": "Back",
    "Anterior Deltoid": "Shoulders",
    "Lateral Deltoid": "Shoulders",
    "Posterior Deltoid": "Shoulders",
    "Rotator Cuff": "Shoulders",
    "Quadriceps": "Legs",
    "Hamstrings": "Legs",
    "Glutes": "Legs",
    "Adductors": "Legs",
    "Calves": "Legs",
    "Biceps Brachii": "Biceps",
    "Brachialis": "Biceps",
    "Brachioradialis": "Biceps",
    "Long Head": "Triceps",
    "Lateral Head": "Triceps",
    "Medial Head": "Triceps",
    "Abdominals": "Core",
}

HARD_MAP = {
    # --- PETTO ---
    "flat db bench": "Flat DB Bench",
    "spinte db": "Flat DB Bench",
    "spinte manubri": "Flat DB Bench",
    "panca piana db": "Flat DB Bench",
    "spinte 20": "20 DB Bench",
    "spinte db 20": "20 DB Bench",
    "spinte manubri 20": "20 DB Bench",
    "spinte 32": "32 DB Bench",
    "spinte db 32": "32 DB Bench",
    "spinte manubri 32": "32 DB Bench",
    "spinte 45": "45 DB Bench",
    "spinte db 45": "45 DB Bench",
    "spinte manubri 45": "45 DB Bench",
    "panca piana": "Flat Barbell Bench",
    "panca piana bil": "Flat Barbell Bench",
    "panca 20": "20 Barbell Bench",
    "panca 32": "32 Barbell Bench",
    "panca 45": "45 Barbell Bench",
    "sm piana": "Flat SM Bench",
    "sm 20": "20 SM Bench",
    "20 sm": "20 SM Bench",
    "sm 32": "32 SM Bench",
    "32 sm": "32 SM Bench",
    "sm 45": "45 SM Bench",
    "45 sm": "45 SM Bench",
    "sm press 30": "30 SM Press",
    "smith 30": "30 SM Press",
    "croci db": "DB Flies",
    "croci manubri": "DB Flies",
    "croci cavo basso": "Low Cable Flies",
    "croci basse": "Low Cable Flies",
    "croci cavo alto": "High Cable Flies",
    "croci alte": "High Cable Flies",
    "croci incl": "Incl Cable Flies",
    "croci cavo incl": "Incl Cable Flies",
    "pec dec": "Pec Deck",
    "butterfly": "Pec Deck",
    "pectoral": "Pec Deck",
    "chest press": "Chest Press",
    # --- DORSO ---
    "lat machine": "Lat Machine",
    "lat presa larga": "Lat Machine",
    "lat": "Lat Machine",
    "lat machine alternative": "Lat Machine Alternative",
    "pulley stretta": "Close Pulley",
    "pulley presa stretta": "Close Pulley",
    "pulley larga": "Wide Pulley",
    "pulley presa larga": "Wide Pulley",
    "pulley sa": "SA Pulley",
    "pulley mono": "SA Pulley",
    "pulley single arm": "SA Pulley",
    "t-bar": "T-Bar",
    "tbar": "T-Bar",
    "t bar": "T-Bar",
    "machine t-bar": "Machine T-Bar",
    "t-bar macch": "Machine T-Bar",
    "pullover": "Pullover",
    "pullover cavo": "Pullover",
    "sa pulldown": "SA Cable Pulldown",
    "single arm pulldown": "SA Cable Pulldown",
    "pulldown cavo": "SA Cable Pulldown",
    "sa machine pulldown": "SA Machine Pulldown",
    "pulldown macch": "SA Machine Pulldown",
    "chin up": "Chin-Ups",
    "max chin up": "Chin-Ups",
    "trazioni": "Chin-Ups",
    # --- SPALLE ---
    "lr": "LR",
    "lr 49": "LR 49",
    "alzate laterali 49": "LR 49",
    "alzate laterali": "LR",
    "lateral raise": "LR",
    "lrc": "LRC",
    "alzate laterali cavo": "LRC",
    "lateral raise cable": "LRC",
    "shoulder press": "Machine Press",
    "press macch": "Machine Press",
    "extra": "Shoulder Extra-Rotations",
    "extra rotazioni": "Shoulder Extra-Rotations",
    # --- GAMBE ---
    "squat": "Squat",
    "back squat": "Squat",
    "pressa": "Leg Press 45",
    "leg press": "Leg Press 45",
    "pressa 45": "Leg Press 45",
    "hack squat": "Hack Squat",
    "hack": "Hack Squat",
    "sissy": "Sissy Squat",
    "sissy squat": "Sissy Squat",
    "rdl": "RDL",
    "stacchi rumeni": "RDL",
    "rumeni": "RDL",
    "stacco gambe tese": "Stiff Leg Deadlift",
    "sldl": "Stiff Leg Deadlift",
    "deadlift": "Deadlift",
    "stacco": "Deadlift",
    "stacco terra": "Deadlift",
    "leg curl": "Leg Curl",
    "leg curl sdraiato": "Leg Curl",
    "leg ext": "Leg Extension",
    "leg extension": "Leg Extension",
    # --- BRACCIA (Bicipiti) ---
    "curl 45": "45 Incl Curl",
    "curl incl 45": "45 Incl Curl",
    "curl 49": "49 Incl Curl",
    "curl incl 49": "49 Incl Curl",
    "hammer db": "DB Hammer",
    "hammer manubri": "DB Hammer",
    "bicipiti hammer": "DB Hammer",
    "preacher": "Preacher Curl",
    "scott": "Preacher Curl",
    "panca scott": "Preacher Curl",
    "biceps curl db reverse scott bench": "Reverse Scott DB Curl",
    "reverse scott db curl": "Reverse Scott DB Curl",
    "spider curl db": "Reverse Scott DB Curl",
    "spider curl manubri": "Reverse Scott DB Curl",
    # --- BRACCIA (Tricipiti) ---
    "fr pr c": "Cable French Press",
    "french press cavo": "Cable French Press",
    "pushdown 54": "Bench 54 Pushdown",
    "pd cavo panca 54": "Bench 54 Pushdown",
    "push down 54": "Bench 54 Pushdown",
    "pushdown incl": "Incl Cable Pushdown",
    "pushdown cavo incl": "Incl Cable Pushdown",
    "low cable triceps": "Low Cable Triceps",
    "tricipiti cavo basso": "Low Cable Triceps",
    "bench 54 triceps": "Bench 54 Triceps",
    "tricipiti panca 54": "Bench 54 Triceps",
    # --- ADDOME ---
    "dragon flag": "Dragon Flag Raises",
    "dragon flag raises": "Dragon Flag Raises",
    "hanging leg": "Hanging Leg Raises",
    "hanging leg raises": "Hanging Leg Raises",
    "leg raises": "Hanging Leg Raises",
    "crunch": "Crunch",
}

SORTED_HARD_MAP_KEYS = sorted(HARD_MAP.keys(), key=len, reverse=True)
